name: Events Demo 1
# on:
#   pull_request:
#     types:
#       - opened
#     branches:
#       - main # main
#       - "dev-*" # dev-new dev-this-is-new
#       - "feat/**" # feat/new feat/new/button
#   workflow_dispatch: # No events but ":" at the end!
#   push:
#     branches:
#       - main # main
#       - "dev-*" # dev-new dev-this-is-new
#       - "feat/**" # feat/new feat/new/button
#       # developer-1
#     paths-ignore:
#       - ".github/workflows/*"
on: workflow_dispatch
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Output event data
        run: echo "${{ toJson(github.event_name) }}"
      - name: Get code
        uses: actions/checkout@v3
      - name: Install dependencies
        working-directory: "./02 GitHub Actions/01"
        run: npm ci
      - name: Test code
        working-directory: "./02 GitHub Actions/01"
        run: npm run test
      - name: Build code
        working-directory: "./02 GitHub Actions/01"
        run: npm run build
      - name: Deploy project
        working-directory: "./02 GitHub Actions/01"
        run: echo "Deploying..."
