name: Handle issues
# on: issues
on: workflow_dispatch
jobs:
  output-info:
    runs-on: ubuntu-latest
    steps:
      - name: Output event details
        run: echo "${{ toJson(github.event_name) }}"
      - name: Output action details
        run: echo "${{ toJson(github.action) }}"
