name: Output information
on: workflow_dispatch
jobs:
  info:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: "./02 GitHub Actions/01_second_action"
    steps:
      - name: Output GitHub context
        run: echo "${{ toJSON(github) }}" # The toJSON() function converts an object into a JSON-formatted string and takes the github context.
